### ISSUE TITLE
fetal error  swift 3.0

### ISSUE THREAD

**Issue by qiusheng2011** [SimonFairbairn/SwiftyMarkdown#33] opened 2016-09-25 03:46 UTC
fatal error: cannot increment beyond endIndex
(lldb)  

tarfromScanner 295

**Comment by stupergenius** [comment] 2016-10-28 19:32
Possible duplicate of #14?

**Comment by chipallen2** [comment] 2016-12-07 20:49
I'm also getting this. Line 295 in function `tagFromScanner`

`let newRange  = hasRange.lowerBound..<matchedCharacters.index(hasRange.upperBound, offsetBy: 1)`

**Comment by markhim** [comment] 2017-01-11 09:30
I can confirm this issue!

String that crashes is "\\+"

**Comment by timgcarlson** [comment] 2017-01-20 00:27
Anyone working on a fix for this? Can't really release an app with this framework if it's going to crash every time the text used begins with "\".

**Comment by ishaanSejwal** [comment] 2017-01-20 01:27
I think you gotta solve this yourself, everyone appears to be busy. I also
have some issues for my use cases which i will be working on later in the
month, got my hands full too currently.

**Comment by DavidLari** [comment] 2017-01-20 02:24
I had to give up on this one and switched to https://github.com/ivanbruel/MarkdownKit. It was an easy change as I think it is derived from this project.

**Comment by timgcarlson** [comment] 2017-01-20 07:08
Thanks @DavidLari!

**Comment by SimonFairbairn** [comment] 2017-04-01 09:50
Should have no problems with \ any longer.

**Closed by SimonFairbairn** 2017-04-01 09:50 UTC
